### ISSUE TITLE
Faulted subscription: System.ReadOnlySpan is invalid for serialization

### ISSUE THREAD

**Issue by bvandewe** [neuroglia-io/cloud-streams#52]
**Describe the bug**

A subscription becomes faulted after it served all events.
Not sure what triggers the sub to become faulted. There is no other significant logs in the broker pod, AFAICT...

Here's the (sanitized) output of the faulted sub:

```yaml
spec:
  partition:
    type: by-source
    id: https://my-source-to-subscribe.com
  stream:
    offset: 0
  subscriber:
    uri: https://my-test-subscriber.com
status:
  phase: active
  observedGeneration: 1
  stream:
    ackedOffset: 5995
    fault:
      type: System.InvalidOperationException
      title: InvalidOperationException
      status: 500
      detail: The type 'System.ReadOnlySpan`1[System.Byte]' of property 'Span' on type 'System.ReadOnlyMemory`1[System.Byte]' is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types.

```
